// src/App.svelte
<script lang="ts">
  import AVRRunner from './execute';
  import matrix from './matrix.svelte';
  import LedMatrix from './LedMatrix.svelte';
  import firmwareUrl from '../build/firmware.ino.with_bootloader.bin?url';

  const messages = [
    ['Alert: Follow', 'AF0\nTestFollow\n'],
    ['Alert: Sub', 'AS0\nTestSub\nNew sub message\n'],
    ['Alert: Resub', 'As12\nTestResub\nResub message\n'],
    ['Alert: Gift', 'AG10\nTestGiftSub\n'],
    ['Alert: Cheer', 'AC1000\nTestCheer\nCheer message\n'],
    ['Alert: Raid', 'AR10000\nTestRaid\nRaid Test\n'],
    ['Label: Follow', 'LF0\nTestFollow\n'],
    ['Label: Sub', 'LS0\nTestSub\n'],
    ['Label: Resub', 'Ls24\nTestResub\n'],
    ['Label: Cheer', 'LC1000\nTestCheer\n'],
  ];
  let runner: AVRRunner;

  fetch(firmwareUrl).then(async response => {
    const firmware = await response.arrayBuffer();
    runner = new AVRRunner(new Uint16Array(firmware));

    runner.spi.onByte = value => {
      matrix.set(value);
      runner.spi.completeTransfer(value);
    };

    runner.usart.onLineTransmit = line => {
      console.log(line);
    };

    runner.execute(() => {});

    return () => {
      runner.stop();
    };
  });
</script>

<main>
  <LedMatrix color="#ff9900" ledWidth={4} ledHeight={5} modules={matrix.zone(0)} />
  <LedMatrix color="#ff9900" ledWidth={4} ledHeight={5} modules={matrix.zone(1)} />
  <LedMatrix color="#ff9900" ledWidth={4} ledHeight={5} modules={matrix.zone(2)} />
  <LedMatrix color="#ff9900" ledWidth={4} ledHeight={5} modules={matrix.zone(3)} />
  <div>
  {#each messages as message}
    <button type="button" onclick={() => { runner.serialWrite(message[1]); }}>{message[0]}</button>
  {/each}
  </div>
</main>

// src/app.tsx
import { render } from 'preact';
import { useEffect } from 'preact/hooks';
import { signal } from '@preact/signals';

import AVRRunner from './execute';
import firmwareUrl from '../build/firmware.ino.with_bootloader.bin?url';

const CHAIN_LENGTH = 10;
const OFF_COLOR = '#444444';

const matrix = signal<Uint8Array[]>([]);

async function runFirmware(response: Response) {
  const firmware = await response.arrayBuffer();
  const runner = new AVRRunner(new Uint16Array(firmware));
  let display = 0;
  let segment: number | null = null;

  for (let i = 0; i < CHAIN_LENGTH; i++) {
    matrix.value.push(new Uint8Array(8));
  }

  runner.spi.onByte = value => {
    if (segment === null) {
      segment = value;
    } else {
      if (segment <= 8) {
        matrix.value[display][segment-1] = value;
      } else {
        console.log('out of bounds: %s %s', segment, value);
      }
      display = (display + 1) % CHAIN_LENGTH;
      segment = null;
    }
    runner.spi.completeTransfer(value);
  };

  runner.execute(() => {
    matrix.value = [...matrix.value]; // flush components
  });
}

function App() {
  const color = '#ff9900';
  const ledWidth = 4;
  const ledHeight = 5;

  useEffect(() => {
    fetch(firmwareUrl).then(runFirmware);
  }, []);

  return (
    <>
      {matrix.value.map(display => (
        <svg xmlns="http://www.w3.org/2000/svg" width={ledWidth * 8} height={ledHeight * 8}>
          {[...display].map((row, y) => [...Array(8).keys()].map(x =>
            <ellipse fill={(row >> x & 1) ? color : OFF_COLOR}
                     rx={ledWidth / 2} ry={ledHeight / 2}
                     cx={ledWidth * (x + 0.5)} cy={ledHeight * (y + 0.5)}/>
          ))}
        </svg>
      ))}
    </>
  )
}

render(<App />, document.getElementById('app')!);
